apiVersion: v1
kind: ServiceAccount
metadata:
  name: "pod-node-label-{{ .Release.Name }}"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: "pod-node-label-{{ .Release.Name }}"
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - nodes
  verbs:
  - list
  - update
  - create
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: "pod-node-label-{{ .Release.Name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "pod-node-label-{{ .Release.Name }}"
subjects:
- kind: ServiceAccount
  name: "pod-node-label-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace | quote }}